### PR TITLE
Fix incorrect return value in DefaultKeyedValues2D#getRowIndex

### PR DESCRIPTION
**Pull request by kelloggm**
DefaultKeyedValues2D#getRowIndex returns the result of Collections.binarySearch directly if the underlying List is being kept in sorted order. The specification for [Collections.binarySearch](https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#binarySearch(java.util.List,%20T)) is unusual: if the element being searched for is not found, a negative index indicating where to insert the value to keep the list in sorted order is returned. The specification on getRowIndex, defined in the KeyedValues2D interface, says:
 ``` * @return The row index, or {@code -1} if the key is unrecognised```. 

This pull request changes DefaultKeyedValues2D#getRowIndex to respect the specification written on KeyedValues2D#getRowIndex; an alternative option would be to change the spec there to allow a negative index to be returned.

### CODE REVIEW

**Comment by tracylynne99** [comment]
Downloaded PR to local branch on 09-feb-2020, awaiting more testing before final merge into master

**Comment by jfree** [comment]
This looks good to me.

**Comment by jfree** [comment]
In fact this causes some tests to fail.  I'm investigating.

**Comment by jfree** [comment]
There is some code relying on the return value from the Collections.binarySearch, so I will go with the other approach (change the documented return value).

**Pull request merged**
