### PR TITLE
Improved mouse handler for zooming only on X axis or only on Y axis

### PR DESCRIPTION
**Pull request by tomas-pluskal**
Hi,
I added a function to zoom in (and out) a single axis by dragging the mouse on that axis.
Hope you like it.

### CODE REVIEW

**Comment by tomas-pluskal** [comment]
Hi,
any chance to have this merged?

**Comment by tomas-pluskal** [comment]
Hi,
any chance to have this merged?

**Comment by tomas-pluskal** [comment]
Now that the project is back to life, can this be merged?

**Comment by jfree** [comment]
Yes, it is done.

**Pull request merged**
