### PR TITLE
Selection zoom strategy implemented to allow changing zooming behavior

### PR DESCRIPTION
**Pull request by DrBAXA**
Changes in this pull request allow overriding zooming by selecting an area by mouse controller.
Code related to zoom rectangle is moved into a separate class that can be easily overridden.

### CODE REVIEW

**Comment by tracylynne99** [comment]
Downloaded PR to local branch on 09-feb-2020, awaiting resolution of merge conflicts and more testing before final merge into master

**Comment by DrBAXA** [comment]
Hi @tracylynne99, thanks for looking at it.

I've rebased this change onto the current master and fixed conflicts. 
This change was needed to implement keep aspect ratio zooming and is just an extraction code to delegate refactoring so the behavior should be unchanged. 
What kinds of tests would you like to see added here?

**Comment by DrBAXA** [comment]
Is there any chance that this pull request will be accepted? 
I'm ready to resolve conflicts and refactor it if there are any questions or wishes.

**Comment by tracylynne99** [comment]
Good question! David, I can do any merging/testing for this if you'd like.
Let me know!

**Comment by jfree** [comment]
Hi Tracy, I'd be happy to hear a second opinion on the change...I haven't had a chance to look in depth at it yet.  But we can do that before the 1.6.0 release (it's going to take at least another couple of weeks I'd say). I'm generally leaning against adding more abstraction to JFreeChart, since it already has enough and it comes with a cost, but I think the area of zooming might be one where adding flexibility could be worth it.  Tell me what you think.
Best regards,
David

**Comment by tracylynne99** [comment]
@jfree  - I reviewed these changes and they look fine to me.  No changes to public methods in ChartPanel, and all of the tests passed.  ChartPanel is a large class, so separating the zoom behavior into another class seems like a good idea to me.

@DrBAXA Could you add a javadoc comment to the new class file? Also, ChartPanel will have to be deconflicted.  NetBeans' visualizer was crap in this particular instance, requires all of one file or all of the other.  And when I took all of the changes from your branch, then did a diff to the master version, it showed something like 58 differences!  I haven't reviewed David's commits closely enough to know for sure which are his changes and which are yours lol!

Hope that helps :-)

**Comment by DrBAXA** [comment]
Thanks for the effort given here. 
I've resolved conflicts and added a javadock.

**Comment by DrBAXA** [comment]
Hi there. 
Is there anything I can do for this pull request to be accepted?

**Comment by jfree** [comment]
You need to have patience and persisten...oh, wait! ;-)

The change looks fine...I will remove the @since tags, since they don't really apply anymore.  And then I'm wondering if the API for DefaultSelectionZoomStrategy should be extracted to an interface.  But I'll merge it as is, and update later.

**Comment by DrBAXA** [comment]
Thanks, David.
I was unsure about extracting an interface as there is only one implementation currently. But this makes sense for someone who will need to implement something own and not depend on the default one. 
Extracted it in PR #218

**Pull request merged**
