### PR TITLE
Fixes extreme zoom (#64)

### PR DESCRIPTION
**Pull request by mayuso**

### CODE REVIEW

**Comment by tracylynne99** [comment]
Downloaded PR to local branch on 09-feb-2020, awaiting more testing before final merge into master

**Comment by vsonnier** [comment]
Allow me to ping this, because indeed we encounter the freezing bug rather often in our application. This fix would be really nice to have.

**Comment by vsonnier** [comment]
Hi @jfree, I'm seeing in  #147 that you are considering a new version. Could you have a look at this, please ? Thanks !

**Comment by jfree** [comment]
Does anyone have some code to trigger this problem?

**Comment by jfree** [comment]
> Does anyone have some code to trigger this problem?

This seems to do it: https://stackoverflow.com/questions/24755750/error-in-jfreechart-creating-numberaxis-with-large-values

**Comment by jfree** [comment]
The suggested change is just ignoring the bad input (infinity) and not addressing where it came from.

**Comment by mayuso** [comment]
It believe it is time to close this PR already. 

As you said, this might not be the best fix and Issue #73 is already open so this problem won't be ignored. Also, I haven't written any java for a couple years now so diving back into this problem and trying to improve my 3 year old fix would take me a lot of time.

**Comment by jfree** [comment]
No problem.  I think I will find a fix for this issue over the weekend.

**Pull request closed without merging**
